export { HeroSection } from './hero-section'
export { AboutSection } from './about-section'
export { PracticeAreasSection } from './practice-areas-section'
export { ProjectsSection } from './projects-section'
export { TechnologiesSection } from './technologies-section'
export { ContactSection } from './contact-section'
